apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compliantpostgresrdsinstances.aws.platform.bfsi
spec:
  group: aws.platform.bfsi
  names:
    kind: CompliantPostgresRDSInstance
    plural: compliantpostgresrdsinstances
  claimNames:
    kind: CompliantPostgresRDSInstanceClaim
    plural: compliantpostgresrdsinstanceclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    instanceClass:
                      type: string
                      default: "db.t3.micro"
                    storageGB:
                      type: integer
                      default: 20
                    username:
                      type: string
                    dbName:
                      type: string
                  required:
                    - username
                    - dbName